import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import holdingsData from '@/data/holdings.json';
import activityData from '@/data/activity.json';
import { allocation, summary } from '@/lib/portfolio';

const dollars=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const pounds=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:2}).format(n);
const date=(s:string)=>new Date(`${s}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
const rows=holdingsData.holdings.filter(h=>['Bonds','Bond funds'].includes(h.section));
const bonds=rows.filter(h=>h.section==='Bonds');
const funds=rows.filter(h=>h.section==='Bond funds');
const value=(r:typeof rows)=>r.reduce((a,h)=>a+(h.value_usd??0)+h.accrued_interest_usd,0);
const total=value(rows);
const bank=allocation.find(x=>x.name==='Bonds')!;
const interest=activityData.estimated_interest.rows.filter(r=>r.instrument==='FLR Barclays WFM');
const labels:Record<string,string>={'holding-031':'Barclays PLC','holding-032':'Ares Strat Inc Offsh','holding-033':'Man Dynamic Income'};

export default function BondsSection(){return <div className="stack">
 <section className="panel"><div className="panelhead"><div><p className="eyebrow">BONDS · STATEMENT SUMMARY</p><h2>One direct bond. Two bond funds.</h2></div><span className="small-label">As of 30 July 2026</span></div><p className="subtitle">The detailed holdings list a Barclays bond and two investment funds. Together they account for {dollars(total)}, including accrued interest.</p>
 <div className="bond-metrics"><article><span>Bank’s overall bond allocation</span><strong>{dollars(bank.value)}</strong><p>{bank.pct.toFixed(2)}% of net portfolio · fund look-through · p. 1</p></article><article><span>Listed bond and bond funds</span><strong>{dollars(total)}</strong><p>{(total/summary.net*100).toFixed(2)}% of net portfolio · including interest · pp. 8–9</p></article><article><span>Direct bond</span><strong>{dollars(value(bonds))}</strong><p>Barclays · including {dollars(2750.36)} accrued interest</p></article><article><span>Two bond funds</span><strong>{dollars(value(funds))}</strong><p>Ares and Man · no separate accrued interest shown</p></article></div>
 <div className="callout"><h3>Why the two bond totals differ</h3><p>The {dollars(bank.value)} allocation uses the bank’s underlying fund allocations where available. The {dollars(total)} total uses the three entries actually listed under “Bonds” and “Bond funds.” Their difference is {dollars(bank.value-total)}. The summary does not map that difference to individual funds.</p></div></section>
 <section className="panel"><p className="eyebrow">THE THREE HOLDINGS · PP. 8–9</p><h2>What is held</h2><div className="bond-composition">{rows.map(h=><div className="allocrow" key={h.id}><div><span>{labels[h.id]??h.name}</span><b>{dollars((h.value_usd??0)+h.accrued_interest_usd)}</b></div><div className="bartrack"><div className="bar" style={{width:`${((h.value_usd??0)+h.accrued_interest_usd)/total*100}%`}}/></div><span>{(((h.value_usd??0)+h.accrued_interest_usd)/total*100).toFixed(1)}%</span></div>)}</div><p className="note">Bars show each holding’s share of the listed bond-and-fund total, including accrued interest.</p>
 <Table><TableHeader><TableRow><TableHead>Holding</TableHead><TableHead>Type / currency</TableHead><TableHead className="num">Market value in USD</TableHead><TableHead className="num">Accrued interest</TableHead><TableHead className="num">Total value in USD</TableHead><TableHead>Price date</TableHead></TableRow></TableHeader><TableBody>{rows.map(h=><TableRow key={h.id}><TableCell className="holding-name"><strong>{labels[h.id]??h.name}</strong><span>{h.description}</span><code>{h.isin} · p. {h.printed_page}</code></TableCell><TableCell>{h.section==='Bonds'?'Direct bond':'Fund'} · {h.currency}</TableCell><TableCell className="num">{dollars(h.value_usd??0)}</TableCell><TableCell className="num">{h.section==="Bond funds"?"Not separately shown":dollars(h.accrued_interest_usd)}</TableCell><TableCell className="num">{dollars((h.value_usd??0)+h.accrued_interest_usd)}</TableCell><TableCell>{h.price_date?date(h.price_date):'Not reported'}</TableCell></TableRow>)}</TableBody></Table><p className="note below">The market values and dates are the bank’s statement figures, not live quotations. The Ares holding uses a 30 June price; Man uses a 29 July price.</p></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">BARCLAYS PLC · P. 8</p><h2>The direct bond at a glance</h2><dl className="bond-facts"><div><dt>Nominal amount</dt><dd>GBP 200,000</dd></div><div><dt>Stated coupon</dt><dd>8.375%</dd></div><div><dt>Bank’s description</dt><dd>Floating rate Eurobond (CoCo bond)</dd></div><div><dt>Final maturity</dt><dd>No fixed final maturity shown</dd></div><div><dt>Statement price</dt><dd>105.92% of nominal</dd></div><div><dt>Purchase price shown</dt><dd>101.25% of nominal</dd></div></dl><p className="note">Nominal amount is the face amount in pounds. Market value is the bank’s USD valuation. The stated coupon and the portfolio’s investment return are different measures.</p></section>
 <section className="panel"><p className="eyebrow">BARCLAYS INTEREST ESTIMATE · PP. 55, 57–59</p><h2>{pounds(interest.reduce((n,r)=>n+r.amount,0))} scheduled in the statement</h2><p className="subtitle">Four estimated payments of {pounds(4187.50)} each. Their combined statement USD equivalent is {dollars(interest.reduce((n,r)=>n+r.statement_amount_usd,0))}.</p><Table><TableHeader><TableRow><TableHead>Scheduled date</TableHead><TableHead className="num">GBP</TableHead><TableHead className="num">USD equivalent</TableHead><TableHead>Page</TableHead></TableRow></TableHeader><TableBody>{interest.map(r=><TableRow key={r.date}><TableCell>{date(r.date)}</TableCell><TableCell className="num">{pounds(r.amount)}</TableCell><TableCell className="num">{dollars(r.statement_amount_usd)}</TableCell><TableCell>p. {r.printed_page}</TableCell></TableRow>)}</TableBody></Table><p className="note below">These are the bank’s estimates as of 30 July, not confirmed receipts. This schedule is for the Barclays bond only; it does not total distributions from the two bond funds.</p></section></div>
 </div>}
