'use client';
import {useMemo,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {holdings,loans,notes,options,structured,metrics,expiryReached,money,percent,date,repaymentIllustration} from '@/lib/risk';
import {optionTerms} from '@/lib/options';
import {StructuredContracts} from './risk';

const actions=[
 ['Confirm the current account before trading','Obtain current option settlements, loan balances after the 7 September statement, available cash, margin and blocked shares.','Prevents treating already-settled obligations or changed loan terms as current. A live position file is needed before execution.'],
 ['Reduce or exit the four 2× contracts','Request a firm termination quote and remaining normal/leveraged purchase obligations for each of the three accumulators and the currency TARF. Compare exit cost with stressed retention obligations.','An exit can crystallize a loss and reduce future upside. The statement mark is neither an executable termination quote nor the maximum obligation.'],
 ['Reduce borrowing through planned asset sales','Use liquid, unencumbered assets or external funds to repay selected advances; start with imminent renewals and currency mismatches. Obtain repayment terms and collateral-release requirements.','Selling assets can realize gains/losses and taxes. Keep a cash buffer for option settlement and fund calls. Do not assume net cash is free collateral.'],
 ['Reduce short-put commitments','For each short put, compare closing or reducing contracts with the purchase cash you can fund. Consider a matching protective put only after pricing the whole position.','Closing may cost cash; protection costs premium. Rolling to a new expiry keeps a liability and is not by itself risk reduction. Confirm matching underlying, expiry and deliverable for any spread.'],
 ['Simplify equity-linked notes and repeated exposures','Review all 18 equity-category notes and exposures repeated through direct shares, funds, puts and accumulators. Consider reducing the most concentrated or least transparent positions.','Obtain issuer, underlying basket, barrier, observation schedule and executable bid. A high coupon does not establish capital protection; early sale spreads can be large.'],
 ['Keep covered calls paired with their covering shares','Check each covered call before selling any covering shares; close or resize both legs together where appropriate.','Closing a covered call alone restores upside but leaves the stock downside. Selling the shares alone can create uncovered call exposure.'],
 ['Match currency funding and preserve liquid reserves','Plan cash by currency and date for loans, potential assignments and capital calls. Confirm remaining callable fund commitments and dealing/redemption terms.','Conversions, hedges and fund exits have costs and may be restricted. A new hedge can itself create margin or counterparty exposure.'],
];
type Item={id:string;kind:string;name:string;value:number;terms:string;action:string;page:number};
const items:Item[]=[
 ...loans.map(h=>({id:h.id,kind:'Loans',name:`${h.currency} advance`,value:h.total_value_usd??0,terms:`${money(Math.abs(h.balance_in_currency??0),h.currency)} principal · ${h.interest_rate_pct}% · maturity ${date(h.maturity_date!)}`,action:'Confirm renewal/current balance and repayment quote. Compare refinancing with funded principal reduction.',page:h.printed_page})),
 ...holdings.filter(h=>h.section==='Accounts (Liquidity)'&&(h.value_usd??0)<0).map(h=>({id:h.id,kind:'Overdrafts',name:h.name,value:h.total_value_usd??0,terms:`${money(Math.abs(h.balance_in_currency??0),h.currency)} principal owed`,action:'Confirm debit balance, rate and available matching-currency cash; repay without exhausting settlement reserves.',page:h.printed_page})),
 ...structured.map(s=>({id:s.id,kind:'2× contracts',name:`${s.underlying} · ${s.type}`,value:s.statement_mark_usd,terms:`${s.leverage}× · maturity ${date(s.maturity)} · remaining obligations unknown`,action:'Obtain termination cost and remaining normal/2× deliveries. Compare close, resize and retain scenarios.',page:s.printed_page})),
 ...options.map(o=>{const t=optionTerms(o);const reached=expiryReached(o);const isLong=o.signed_contracts>0;return {id:o.id,kind:reached?'Expiry reached':isLong?'Long options':o.type==='Put'?'Later-expiry puts':'Short calls',name:`${o.underlying} ${o.type.toLowerCase()} · ${o.strike} ${o.currency} · ${date(o.expiration)}`,value:o.statement_mark_usd,terms:isLong?`${t.contracts} contracts · purchased right; no holder assignment liability`:`${t.contracts} contracts · ${o.type==='Put'?'pay':'receive'} ${money(t.grossStrikeCash,o.currency,2)} for ${t.shares.toLocaleString()} shares${t.deliverableCash?` + ${money(t.deliverableCash,o.currency,2)} deliverable cash`:''} if fully assigned`,action:reached?'Confirm exercise, assignment and settlement outcome.':isLong?'Compare the cost and remaining optionality of retaining or closing the purchased contract.':o.type==='Put'?'Obtain buyback quote. Close or reduce to a fundable purchase commitment; reserve settlement currency.':'Verify matching shares remain blocked. Coordinate any share sale with closing or resizing the call.',page:o.printed_page}}),
 ...notes.map(h=>({id:h.id,kind:'Equity-linked notes',name:h.name,value:h.total_value_usd??0,terms:`${h.currency} · maturity ${h.maturity_date?date(h.maturity_date):'not provided'}`,action:'Get full terms and secondary-market bid. Review issuer, underlying/barriers and overlap; compare sale cost with retention risk.',page:h.printed_page})),
];

export default function ReduceRisk(){const [query,setQuery]=useState('');const [kind,setKind]=useState('All');const [page,setPage]=useState(0);const [repay,setRepay]=useState(1000000);const filtered=useMemo(()=>items.filter(i=>(kind==='All'||i.kind===kind)&&`${i.name} ${i.terms} ${i.action}`.toLowerCase().includes(query.toLowerCase())),[query,kind]);const illustration=repaymentIllustration(repay);return <div className="stack">
 <section className="panel"><p className="eyebrow">RISK REDUCTION · 7 SEPTEMBER 2026 SNAPSHOT</p><h2>A practical review and action list</h2><p className="subtitle">First establish current obligations. Then reduce the commitments most likely to require cash in a falling market. The sequence below is a review priority, not an instruction to execute every sale.</p><p className="note below">No trades, lender requests or payments are sent by this dashboard. Costs, tax lots, investor objectives and current account terms are not available.</p></section>
 <section className="panel"><h2>Priorities, actions and tradeoffs</h2><ol className="action-list">{actions.map(([title,action,tradeoff])=><li key={title}><h3>{title}</h3><p>{action}</p><p className="note">{tradeoff}</p></li>)}</ol></section>
 <section className="panel"><p className="eyebrow">ILLUSTRATIVE REPAYMENT · NOT A TARGET RECOMMENDATION</p><h2>See how a funded loan repayment changes leverage</h2><p className="subtitle">Advances start at {money(metrics.advances)} or {percent(metrics.advances)} of net assets.</p><label className="risk-slider" htmlFor="repayment-slider">Repayment from assets sold at statement value: <strong>{money(repay)}</strong><input id="repayment-slider" type="range" aria-label="Illustrative advance repayment" min="0" max="4000000" step="100000" value={repay} onChange={e=>setRepay(Number(e.target.value))}/></label><div className="scenario-result" aria-live="polite"><span>Remaining advances / unchanged net assets</span><strong>{money(illustration.remainingAdvances)} · {illustration.ratio.toFixed(2)}%</strong></div><p className="note below">Selling an asset and repaying an equal liability leaves net assets unchanged before costs and taxes. This only reduces fixed advances; overdrafts remain separate. It assumes enough saleable, unencumbered assets and lender consent where required. It does not fund put assignments or imply the remaining risk is acceptable.</p></section>
 <StructuredContracts/>
 <section className="panel"><p className="eyebrow">ITEMIZED POSITION REVIEW</p><h2>{items.length} individual review items</h2><p className="subtitle">Every listed option, advance, negative cash balance, 2× contract and equity-category structured note. Signed marks are statement USD values; obligation amounts keep their native currency.</p><div className="filters"><label className="searchfield" htmlFor="risk-search"><span className="fieldlabel">Find a position</span><Input id="risk-search" placeholder="Symbol, currency, maturity or action" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label className="picker" htmlFor="risk-category"><span className="fieldlabel">Review category</span><select id="risk-category" aria-label="Review category" value={kind} onChange={e=>{setKind(e.target.value);setPage(0)}}>{['All',...new Set(items.map(i=>i.kind))].map(k=><option key={k}>{k}</option>)}</select></label><Button variant="outline" onClick={()=>{setQuery('');setKind('All');setPage(0)}}>Reset</Button></div><p className="note below" aria-live="polite">{filtered.length} matching review items</p><Table><TableHeader><TableRow><TableHead>Position / source</TableHead><TableHead className="num">Signed mark · USD</TableHead><TableHead>Terms / obligation</TableHead><TableHead>Specific next action</TableHead></TableRow></TableHeader><TableBody>{filtered.slice(page*15,(page+1)*15).map(i=><TableRow key={i.id}><TableCell className="holding-name"><strong>{i.name}</strong><span>{i.kind} · p. {i.page}</span></TableCell><TableCell className="num">{money(i.value,'USD',2)}</TableCell><TableCell className="wrap risk-table-text">{i.terms}</TableCell><TableCell className="wrap risk-table-text">{i.action}</TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<p className="empty">No matching positions. Clear the filters to see all items.</p>}<div className="paginationbar"><span>{filtered.length?`${page*15+1}–${Math.min((page+1)*15,filtered.length)} of ${filtered.length}`:'0 items'}</span><div className="option-paging"><Button variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={(page+1)*15>=filtered.length} onClick={()=>setPage(page+1)}>Next</Button></div></div><p className="note">Put strike payments buy shares and are not loss estimates. Covered-call proceeds are received against share delivery. Marks should not be summed with purchase cash to create a “total risk” figure.</p></section>
 <section className="panel"><h2>What to request from LGT</h2><ul className="risk-list"><li>Current positions, cash available for withdrawal, blocked collateral, credit limits, haircuts and margin-call stress calculations.</li><li>Assignment confirmations, related share deliveries and FX movements; current loan balances and repayment costs.</li><li>Individual executable close-out quotes and normal/2× remaining obligations for all four leveraged contracts.</li><li>Each structured note’s issuer, maturity, underlying basket, barriers, observation dates and downside/redemption terms.</li><li>Fund redemption windows, remaining callable commitments and a combined exposure report across shares, funds and derivatives.</li></ul><p className="note below">These requests resolve the main uncertainties before ranking exact trades. <a href="https://www.optionseducation.org/referencelibrary/faq/options-assignment" target="_blank" rel="noreferrer">Assignment mechanics ↗</a> · <a href="https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-76" target="_blank" rel="noreferrer">Structured-note risks ↗</a></p><a className="risk-link" href="#risk">Return to the risk analysis →</a></section>
 </div>}
