'use client';
import {summary,months} from '@/lib/portfolio';
import {money} from '@/lib/risk';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';

const pct=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;
export default function ReturnDrivers(){const best=[...months].sort((a,b)=>b.pct-a.pct)[0];const worst=[...months].sort((a,b)=>a.pct-b.pct)[0];return <div className="stack">
 <section className="panel"><p className="eyebrow">QUESTION 9 · RETURN DRIVERS</p><h2>What produced the return, and can it continue?</h2><p className="subtitle">The replacement statement reports the result and monthly path, but it does not attribute performance by holding, strategy, borrowing or option activity.</p><div className="option-metrics"><article><span>2026 return through 7 September</span><strong>{pct(summary.returnPct)}</strong><p>Bank-reported time-weighted return</p></article><article><span>Investment change</span><strong>{money(summary.investmentChange)}</strong><p>Separate from deposits and withdrawals</p></article><article><span>Ending value</span><strong>{money(summary.performanceEnd)}</strong><p>Reconciles to the holdings total</p></article></div></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">MONTHLY PATH · PRINTED P. 3</p><h2>Strong gains with large reversals</h2><Table><TableHeader><TableRow><TableHead>Period</TableHead><TableHead className="num">Return</TableHead><TableHead className="num">Investment change</TableHead><TableHead className="num">Ending value</TableHead></TableRow></TableHeader><TableBody>{months.map(m=><TableRow key={m.label}><TableCell>{m.label}</TableCell><TableCell className={`num ${m.pct<0?'negative-text':'positive'}`}>{pct(m.pct)}</TableCell><TableCell className={`num ${m.change<0?'negative-text':''}`}>{money(m.change,'USD',2)}</TableCell><TableCell className="num">{money(m.end,'USD',2)}</TableCell></TableRow>)}</TableBody></Table></section><section className="panel"><p className="eyebrow">VOLATILITY SIGNAL</p><h2>{best.label} was {pct(best.pct)}; {worst.label} was {pct(worst.pct)}</h2><p>The spread between the best and worst reported monthly returns is {(best.pct-worst.pct).toFixed(2)} percentage points. That is a wide path for a portfolio intended to compound steadily.</p><p className="note below">This is a descriptive range across nine reported periods, not annualized volatility or maximum drawdown. Those measures require a longer, consistently dated return series.</p></section></div>
 <section className="panel"><h2>Three drivers that remain mixed together</h2><div className="risk-findings"><article><h3>Market exposure</h3><p>Equities are 113.94% of net value, so broad and company-specific equity moves can dominate results.</p></article><article><h3>Borrowing</h3><p>Borrowing can increase gains on financed assets and magnify losses. The statement gives ending balances and rates, not a daily financed-asset return bridge.</p></article><article><h3>Options and structured products</h3><p>Marks, premiums, settlements and later obligations are not separated into realized and unrealized strategy performance.</p></article><article><h3>Cash flows</h3><p>{money(summary.deposits)} of deposits and {money(summary.withdrawals)} of withdrawals change the account balance but are distinct from investment return.</p></article></div></section>
 <section className="panel"><p className="eyebrow">WHAT THE STATEMENT CAN SUPPORT</p><h2>Performance is positive; repeatability is unproven</h2><div className="bridge"><div><span>Starting value</span><b>{money(summary.start,'USD',2)}</b></div><div><span>Net external flows</span><b>{money(summary.deposits+summary.withdrawals,'USD',2)}</b></div><div><span>Investment change</span><b>{money(summary.investmentChange,'USD',2)}</b></div><div><span>Ending value</span><b>{money(summary.performanceEnd,'USD',2)}</b></div></div><p className="note below">The statement provides no holding-level contribution table, transaction ledger, complete cost breakdown or matched benchmark history. A reliable answer needs dated positions and trades, daily or monthly borrowing, option premium and settlement records, and a policy benchmark chosen before evaluating results.</p></section>
 <section className="panel"><h2>Questions to send LGT</h2><ul className="risk-list"><li>Provide a return bridge separating asset allocation, security selection, FX, financing, options, structured notes and accumulators.</li><li>Show gross return, all fees and borrowing cost, and net return using the same dates.</li><li>Provide a matched unleveraged comparison and explain its assumptions.</li><li>Show monthly drawdowns and collateral usage during the largest losses.</li><li>Separate option premiums, realized settlements and ending marked values.</li></ul><a className="risk-link" href="#exposure">See where exposures overlap →</a></section>
 </div>}
