'use client';

import {useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import portfolio from '@/data/portfolio.json';
import benchmarkData from '@/data/return-analysis.json';
import {money} from '@/lib/risk';

type Comparison={label:string;portfolio_return_pct:number;reference_return_pct:number;period_start:string;period_end:string;source_url:string};
const comparisons=benchmarkData.benchmarks as Comparison[];
const pp=(n:number)=>`${n>0?'+':''}${n.toFixed(2)} pp`;
const pct=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;
const contributions=portfolio.performanceContributions;
function growth(rows:Comparison[]){let own=100,reference=100;return [{label:'Start',own,reference},...rows.map(r=>{own*=1+r.portfolio_return_pct/100;reference*=1+r.reference_return_pct/100;return {label:r.label,own,reference}})]}

function GrowthChart({rows}:{rows:Comparison[]}){const values=growth(rows);const min=Math.min(50,...values.flatMap(v=>[v.own,v.reference]));const max=Math.max(...values.flatMap(v=>[v.own,v.reference]))*1.08;const x=(i:number)=>60+i/(values.length-1)*620;const y=(v:number)=>230-(v-min)/(max-min)*195;return <figure className="growth-chart"><svg viewBox="0 0 720 295" role="img" aria-label="Growth of a hypothetical 100 dollars, portfolio versus global equity reference. Exact annual returns are provided in the table below.">{[min,(min+max)/2,max].map(v=><g key={v}><line x1="60" x2="680" y1={y(v)} y2={y(v)} stroke="#dbe3ec"/><text x="50" y={y(v)+4} textAnchor="end">${v.toFixed(0)}</text></g>)}{['own','reference'].map((key,j)=><polyline key={key} fill="none" stroke={j===0?'#173e5a':'#168e83'} strokeWidth="3" strokeDasharray={j?'7 4':undefined} points={values.map((v,i)=>`${x(i)},${y(v[key as 'own'|'reference'])}`).join(' ')}/>)}{values.map((v,i)=><text key={v.label} x={x(i)} y="258" textAnchor="middle">{v.label}</text>)}</svg><figcaption><span><i className="legend-dot own"/>VIV portfolio · bank net return</span><span><i className="legend-dot reference"/>iShares ACWI ETF · USD NAV total return</span></figcaption></figure>}

export default function ReturnDrivers(){const[start,setStart]=useState('2022');const annual=comparisons.filter(r=>/^20\d\d$/.test(r.label));const selected=annual.filter(r=>r.label>=start);const trail=growth(selected);const end=trail[trail.length-1];const loss2022=annual.find(r=>r.label==='2022')!;const gain2023=annual.find(r=>r.label==='2023')!;const cashCosts=-portfolio.components.filter(c=>['Debit interest','Expenses and charges'].includes(c.name)).reduce((s,c)=>s+c.value,0);const maxContribution=Math.max(...contributions.map(c=>Math.abs(c.contribution_pp)));return <div className="stack">
 <section className="panel"><p className="eyebrow">QUESTION 9 · RETURN DRIVERS</p><h2>Strong recent returns; the source of skill is unproven</h2><p className="subtitle">The statement explains returns by asset category and records costs. It does not separate investment selection, leverage and option-writing profit into independently measured contributions.</p><div className="option-metrics"><article><span>2026 return through 23 August</span><strong>{pct(portfolio.summary.returnPct)}</strong><p>Bank-reported net time-weighted return</p></article><article><span>Equity category contribution</span><strong>+12.79 pp</strong><p>Contribution to the portfolio return, not the equity bucket’s own return</p></article><article><span>Derivatives contribution</span><strong>+4.33 pp</strong><p>All bank-classified derivatives; not identified put premiums</p></article></div></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">BANK ATTRIBUTION · PRINTED P. 3</p><h2>What added to the 17.64% return?</h2><div className="contribution-list">{contributions.map(c=><div className="contribution-row" key={c.name}><span>{c.name}</span><div><i className={c.contribution_pp<0?'negative':''} style={{width:`${Math.abs(c.contribution_pp)/maxContribution*100}%`}}/></div><b className={c.contribution_pp<0?'negative-text':'positive'}>{pp(c.contribution_pp)}</b></div>)}</div><p className="note below">The bank’s rounded contributions sum to 17.64 percentage points. Its attribution methodology and look-through categories are retained. Do not add these to the reported return again.</p></section><section className="panel"><p className="eyebrow">DOLLAR RECONCILIATION · PRINTED P. 2</p><h2>{money(portfolio.summary.investmentChange)} investment gain after recorded costs</h2><div className="bridge components">{portfolio.components.map(c=><div key={c.name}><span>{c.name}</span><b className={c.value<0?'negative-text':''}>{money(c.value,'USD',2)}</b></div>)}</div><p className="note below">Debit interest and the expenses line total {money(cashCosts,'USD',2)} and are already deducted. Transaction costs are embedded in price gains; fund expenses, spreads and other embedded costs are not fully itemized. The coupon/dividend line does not isolate option premiums. Dollar changes divided by ending net assets are not time-weighted return contributions.</p></section></div>
 <section className="panel"><h2>Three questions, three different levels of evidence</h2><div className="risk-findings"><article><h3>Did investment selection add value?</h3><p>Not established. Positive equity contribution can reflect broad market gains, sector choices, individual selection and changing position sizes. A holdings snapshot cannot separate these effects.</p><p className="note">Needed: dated holdings/weights, cash flows and a pre-agreed policy benchmark with allocation-versus-selection attribution.</p></article><article><h3>How much did borrowing contribute?</h3><p>The credit category subtracts 0.81 percentage points in the bank’s attribution, and debit interest is {money(58976.35,'USD',2)}. Neither measures the total return effect of borrowing: gains or losses on financed assets appear elsewhere.</p><p className="note">Needed: borrowing balances, rates, FX and financed positions through time. Simply dividing the return by today’s leverage or adding back interest does not recreate an unleveraged portfolio.</p></article><article><h3>How much came from selling downside protection?</h3><p>The derivatives category adds 4.33 percentage points. It includes more than short puts. The statement does not give a strategy-level ledger of premiums, realized gains/losses, buybacks, settlements and changes in marked values.</p><p className="note">Cash premium received is not automatically profit; obligations remain until closed or settled. Covered calls also have different economics from short puts. <a href="https://www.optionseducation.org/strategies/all-strategies/cash-secured-put" target="_blank" rel="noreferrer">OIC: short-put economics ↗</a></p></article><article><h3>Were the returns worth the risk?</h3><p>The comparison below puts the results beside an unleveraged global-equity investment. It helps assess the outcome, but differences in asset mix, currencies, leverage and liquidity prevent calling the gap “manager alpha.”</p><p className="note">Daily or monthly strategy returns and exposure histories are needed for volatility, maximum drawdown and risk-adjusted attribution.</p></article></div></section>
 <section className="panel"><div className="panelhead"><div><p className="eyebrow">MATCHED PERIODS · USD TOTAL RETURNS</p><h2>How did it compare with global equities?</h2></div><div className="picker"><span className="fieldlabel">Growth comparison begins</span><Select value={start} onValueChange={v=>{if(v)setStart(v)}}><SelectTrigger aria-label="Growth comparison begins"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="2019">2019 · seven full years</SelectItem><SelectItem value="2022">2022 · loss and recovery</SelectItem></SelectContent></Select></div></div><p className="subtitle">Reference: iShares MSCI ACWI ETF, an unleveraged global-equity fund. Its USD NAV total returns reinvest distributions and include fund operating expenses. The portfolio uses the bank’s net returns.</p><GrowthChart rows={selected}/><div className="bond-metrics"><article><span>Hypothetical $100 in the portfolio</span><strong>{money(end.own,'USD',2)}</strong><p>{start}–2025 · linked net returns, excluding external deposits and withdrawals</p></article><article><span>Hypothetical $100 in the reference</span><strong>{money(end.reference,'USD',2)}</strong><p>Same calendar periods · distributions reinvested</p></article></div><Table><TableHeader><TableRow><TableHead>Matched period</TableHead><TableHead className="num">VIV portfolio</TableHead><TableHead className="num">Global-equity reference</TableHead><TableHead className="num">Difference</TableHead><TableHead>Reference source</TableHead></TableRow></TableHeader><TableBody>{comparisons.map(r=><TableRow key={r.label}><TableCell>{r.label}</TableCell><TableCell className={`num ${r.portfolio_return_pct<0?'negative-text':''}`}>{pct(r.portfolio_return_pct)}</TableCell><TableCell className="num">{pct(r.reference_return_pct)}</TableCell><TableCell className={`num ${r.portfolio_return_pct-r.reference_return_pct<0?'negative-text':'positive'}`}>{pp(r.portfolio_return_pct-r.reference_return_pct)}</TableCell><TableCell><a href={r.source_url} target="_blank" rel="noreferrer">iShares ↗</a></TableCell></TableRow>)}</TableBody></Table><p className="note below">This is a transparent equity reference, not an agreed benchmark for a mixed portfolio of bonds, private funds, notes and derivatives. ETF returns exclude personal tax, advisory fees and trading costs paid by an investor. A dollar comparison compounds published rounded returns; it is not the account’s actual value history. No unmatched August-end return is compared with the 23 August statement.</p></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">THE 2022 LOSS</p><h2>A large loss requires a larger percentage recovery</h2><p className="below">VIV lost {Math.abs(loss2022.portfolio_return_pct).toFixed(2)}% in 2022, versus {Math.abs(loss2022.reference_return_pct).toFixed(2)}% for the reference. Its {pct(gain2023.portfolio_return_pct)} return in 2023 did not by itself restore the starting value.</p><div className="scenario-result"><span>Gain required after a 42.47% loss to recover</span><strong>{((1/(1+loss2022.portfolio_return_pct/100)-1)*100).toFixed(2)}%</strong><p>$100 fell to $57.53. A 37.58% rebound then brought it to {money(100*(1+loss2022.portfolio_return_pct/100)*(1+gain2023.portfolio_return_pct/100),'USD',2)}.</p></div><p className="note">The 2022 figure is a calendar-year return, not measured peak-to-trough drawdown. Today’s positions cannot establish which 2022 holdings, leverage or trades caused that loss.</p></section><section className="panel"><p className="eyebrow">THE RECENT GAIN</p><h2>2026 is positive, but not a complete attribution</h2><p className="below">The portfolio returned +11.63% through 30 June and +17.64% through 23 August. The matched June comparison is shown above; no exact August comparison is claimed.</p><p className="below">Investment gains of {money(portfolio.summary.investmentChange)} exceeded net withdrawals of {money(-portfolio.summary.withdrawals-portfolio.summary.deposits)}, leaving the performance balance up {money(portfolio.summary.performanceEnd-portfolio.summary.start)}. Account balance growth and investment return answer different questions.</p><p className="note below">The allocation ending value differs from the performance ending value by {money(portfolio.summary.performanceEnd-portfolio.summary.net,'USD',2)}. Both remain as reported. Recent recovery does not guarantee continued growth.</p></section></div>
 <section className="panel"><h2>The evidence to request from LGT</h2><ul className="risk-list"><li>A returns bridge separating asset allocation, selection, financing, FX, short puts, covered calls, notes and accumulators.</li><li>A same-period, after-cost unleveraged counterfactual with its assumptions, supported by dated positions and trades.</li><li>The 2022 monthly drawdown and loss attribution, with the borrowing and collateral history at the time.</li><li>A policy benchmark reflecting the intended asset mix and risk budget, plus all-in fees and embedded product costs.</li></ul><a className="risk-link" href="#exposure">See where exposures overlap →</a></section>
 </div>}
