'use client';
import {useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {metrics,nav,loans,notes,privateFunds,structured,laterOptions,laterPuts,laterCalls,reachedOptions,money,percent,date,equityStress} from '@/lib/risk';
import {summary,coverage} from '@/lib/portfolio';

export function StructuredContracts(){return <section className="panel"><p className="eyebrow">FOUR ACCUMULATORS + ONE CURRENCY TARF · PP. 56–57</p><h2>The five contracts explicitly labeled 2×</h2><p className="subtitle">Combined statement mark: {money(metrics.structuredMark,'USD',2)}. None has a determinable remaining purchase obligation from this statement alone.</p><Table><TableHeader><TableRow><TableHead>Contract</TableHead><TableHead>Printed levels</TableHead><TableHead>Final maturity</TableHead><TableHead className="num">Statement mark · USD</TableHead><TableHead>Ask LGT for each contract</TableHead></TableRow></TableHeader><TableBody>{structured.map(s=><TableRow key={s.id}><TableCell className="holding-name"><strong>{s.underlying}</strong><span>{s.type} · {s.leverage}× · {s.currency} · p. {s.printed_page}</span></TableCell><TableCell className="wrap">{s.stated_level!==null?<>Level {s.stated_level}<br/>Knock-out {s.knock_out_level}</>:<>Lower 143 · pivot 149 · upper 160<br/>European kick-in</>}</TableCell><TableCell>{date(s.maturity)}</TableCell><TableCell className="num">{money(s.statement_mark_usd,'USD',2)}</TableCell><TableCell className="wrap risk-table-text">Executable termination quote, remaining fixing dates, normal and 2× quantities, maximum remaining cash/delivery obligation and collateral requirements.</TableCell></TableRow>)}</TableBody></Table><p className="note below">The displayed levels are labels transcribed from the statement, not a complete payoff formula. Quantities in the source “Units / Nominal value” column do not establish remaining deliveries. The USD/JPY pivot TARF also needs both currency legs, target accrual and knock-in/termination terms. <a href="https://www.ifec.org.hk/web/en/blog/2022/12/accumulators-and-decumulators-2.page" target="_blank" rel="noreferrer">IFEC: accumulator mechanics ↗</a></p></section>}

export default function RiskAnalysis(){const [drop,setDrop]=useState(20);const stress=equityStress(drop);return <div className="stack">
 <section className="panel risk-intro"><div><p className="eyebrow">RISK ANALYSIS · 23 AUGUST 2026 SNAPSHOT</p><h2>High risk</h2><p className="subtitle">The portfolio combines substantial borrowing with equity exposure, short puts and leveraged structured contracts. A market decline can reduce collateral while increasing funding needs.</p></div><span className="risk-rating">HIGH</span><p className="note">Analytical judgment from the supplied statement, not an LGT rating, a predicted loss or a suitability assessment. “High” means several material market and funding risks can reinforce one another. A numerical score would imply more precision than the available terms support.</p></section>
 <section className="risk-grid" aria-label="Main risk measurements">
 {[['Loans including interest',money(metrics.advances),`${percent(metrics.advances)} of net assets · ${loans.length} advances`],['Bank equity allocation',money(metrics.equity),`${percent(metrics.equity)} of net assets · includes fund allocation`],['Later-expiry put purchases',money(metrics.futurePutCash),`${laterPuts.length} positions · gross strike payments at fixed FX`],['Net cash in statement',money(metrics.netCash),`${percent(metrics.netCash)} of net assets · availability unverified`]].map(([label,value,note])=><article className="risk-metric" key={label}><span>{label}</span><strong>{value}</strong><p>{note}</p></article>)}
 </section>
 <section className="panel"><p className="eyebrow">REPORT FINDINGS</p><h2>What drives the rating</h2><div className="risk-findings">
 <article><h3>1. Borrowing and near-term refinancing</h3><p>The eight advances total {money(metrics.advances,'USD',2)}, with statement maturities from 26–31 August, only 3–8 days after the snapshot. Repayment or renewal since then is unknown. Principal overdrafts add {money(metrics.overdraftPrincipal,'USD',2)}. These are separate liabilities within the net portfolio total.</p><p className="note">A collateral decline can prompt demands for more collateral or asset sales; actual thresholds require LGT’s lending terms. <a href="https://www.finra.org/investors/insights/securities-backed-lines-credit" target="_blank" rel="noreferrer">General collateral-loan mechanics ↗</a> · statement pp. 6–9</p></article>
 <article><h3>2. Equity losses can be amplified</h3><p>The bank allocates {percent(metrics.equity)} of net assets to equities. Numerous holdings do not ensure independent risks: funds, direct shares, puts and structured products can respond to the same market or underlying. This allocation is not an option delta or full economic exposure.</p><p className="note">Statement p. 1. Structured notes below overlap this allocation and must not be added as a separate asset exposure.</p></article>
 <article><h3>3. Short puts create purchase obligations</h3><p>{laterPuts.length} puts expire after the statement date. Full assignment across those dates would require about {money(metrics.futurePutCash)} in gross strike payments, {percent(metrics.futurePutCash)} of net assets. That exceeds the {money(metrics.netCash)} net cash balance. Shares received retain a market value; gross purchase cash is not a loss estimate or an immediate cash call.</p><p className="note">No dedicated cash reserve is verified. Original premiums and current margin are not included. American-style options can be assigned early. <a href="https://www.optionseducation.org/referencelibrary/faq/options-assignment" target="_blank" rel="noreferrer">OIC: assignment ↗</a> · pp. 35–55</p></article>
 <article><h3>4. Structured products add conditional losses</h3><p>{notes.length} equity-category notes carry {money(metrics.notes)} of value including interest, {percent(metrics.notes)} of net assets. Issuer credit, conditional redemption, barriers and secondary-market liquidity need review. The five separate 2× contracts can create cash or delivery obligations whose remaining amounts are not supplied.</p><p className="note"><a href="https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-76" target="_blank" rel="noreferrer">SEC: structured notes ↗</a> · statement equity-note entries and pp. 56–57</p></article>
 <article><h3>5. Currency and liquidity need a funding plan</h3><p>Loans are spread across seven currencies; most positive cash is USD. Matching cash to liabilities may require FX transactions. The {privateFunds.length} directly listed private-equity funds have {money(metrics.privateFunds)} of value; fund dealing terms, current valuations and future capital calls need confirmation.</p><p className="note">Private-fund holdings differ from the bank’s look-through private-equity allocation. Older prices do not by themselves prove a valuation is wrong. Net cash is not verified unencumbered cash.</p></article>
 </div></section>
 <section className="panel"><p className="eyebrow">KEEP THE DATE GROUPS SEPARATE</p><h2>147 options listed does not mean 147 active positions today</h2><Table><TableHeader><TableRow><TableHead>Group at 23 August</TableHead><TableHead className="num">Positions</TableHead><TableHead className="num">Put strike payments · USD</TableHead><TableHead>Interpretation</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Expiry later than the snapshot</TableCell><TableCell className="num">{laterOptions.length}</TableCell><TableCell className="num">{money(metrics.futurePutCash,'USD',2)}</TableCell><TableCell className="wrap">{laterPuts.length} puts + {laterCalls.length} calls. Subsequent changes unconfirmed.</TableCell></TableRow><TableRow><TableCell>Expiry already reached</TableCell><TableCell className="num">{reachedOptions.length}</TableCell><TableCell className="num">{money(metrics.reachedPutCash,'USD',2)}</TableCell><TableCell className="wrap">Historical terms only. Confirm settlement and resulting cash/shares before acting.</TableCell></TableRow></TableBody></Table><p className="note below">USD equivalents use statement FX. Totals span expirations and do not establish simultaneous assignment. Calls involve delivering shares in return for strike proceeds, so are excluded from put purchase cash. <a href="#options">Open every option and its expiration calculator →</a></p></section>
 <StructuredContracts/>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">ILLUSTRATION · NOT A FORECAST</p><h2>If the equity allocation loses value</h2><label className="risk-slider">Assumed fall in the bank’s equity allocation: <strong>{drop}%</strong><input aria-label="Equity allocation value decline" type="range" min="0" max="50" step="5" value={drop} onChange={e=>setDrop(Number(e.target.value))}/></label><div className="scenario-result" aria-live="polite"><span>Illustrated fall in net assets</span><strong>{money(stress.loss)} · {stress.navDeclinePct.toFixed(2)}%</strong><p>Net value falls from {money(nav)} to {money(stress.remaining)}.</p></div><p className="note below">Only the bank equity bucket changes; all other assets, liabilities and FX stay fixed. This is a value haircut, not a market-index move. It excludes additional option losses, accumulator deliveries, forced sales, note-specific barriers and costs. It is not a portfolio stress limit or maximum loss.</p></section>
 <section className="panel"><p className="eyebrow">MITIGANTS AND GROWTH CONTEXT</p><h2>There are buffers, with limits</h2><p>Positive cash including accrual is {money(metrics.positiveCash)}; negative account values of {money(metrics.negativeCash)} reduce this to {money(metrics.netCash)} net liquidity. Collateral restrictions and currency conversions may limit access.</p><p className="below">All {laterCalls.length} later-expiry calls are explicitly marked covered in the statement. Coverage reduces share-delivery risk while the matching shares remain held, but those shares still carry downside risk.</p><p className="below">The bank reports +{summary.returnPct.toFixed(2)}% for 1 January–23 August 2026. Its historical 2022 return was −42.47%. A strong recent gain does not establish steady future growth or remove leverage risk.</p><p className="note below">Income schedules are estimates, not guaranteed receipts. No growth forecast is used in this assessment.</p></section></div>
 <section className="panel"><h2>What could change this assessment</h2><ul className="risk-list">{coverage.missing.map(x=><li key={x}>{x}</li>)}<li>Confirmed option settlements, coverage, concentration across funds and structured products, and remaining callable fund commitments.</li></ul><p className="note below">The performance end value exceeds the holdings total by {money(summary.performanceEnd-summary.net,'USD',2)}. Ratios here use the reconciled holdings net value {money(nav,'USD',2)}. Source pages do not explain the difference.</p><a className="risk-link" href="#reduce-risk">Open the itemized risk-reduction plan →</a></section>
 </div>}

