'use client';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {metrics,nav,loans,structured,laterPuts,money,date,equityStress} from '@/lib/risk';
import {summary,coverage,allocation,currencies} from '@/lib/portfolio';

export function StructuredContracts(){return <section className="panel"><p className="eyebrow">THREE ACCUMULATORS + ONE CURRENCY TARF · PP. 51–52</p><h2>Four contracts explicitly labeled 2×</h2><p className="subtitle">Combined statement mark: {money(metrics.structuredMark,'USD',2)}. Their small marked values do not measure the remaining delivery or purchase obligations.</p><Table><TableHeader><TableRow><TableHead>Contract</TableHead><TableHead>Printed levels</TableHead><TableHead>Final maturity</TableHead><TableHead className="num">Statement mark · USD</TableHead><TableHead>Information still needed</TableHead></TableRow></TableHeader><TableBody>{structured.map(s=><TableRow key={s.id}><TableCell className="holding-name"><strong>{s.underlying}</strong><span>{s.type} · {s.leverage}× · {s.currency} · p. {s.printed_page}</span></TableCell><TableCell className="wrap">{s.stated_level!==null?<>Level {s.stated_level}<br/>Knock-out {s.knock_out_level}</>:<>Lower {s.levels?.LS} · pivot {s.levels?.PS} · upper {s.levels?.US}<br/>European kick-in</>}</TableCell><TableCell>{date(s.maturity)}</TableCell><TableCell className="num">{money(s.statement_mark_usd,'USD',2)}</TableCell><TableCell className="wrap">Termination quote, remaining fixing dates and quantities, maximum remaining cash or delivery obligation, and collateral requirement.</TableCell></TableRow>)}</TableBody></Table><p className="note below">The displayed levels are labels from the statement, not a complete payoff formula. <a href="https://www.ifec.org.hk/web/en/blog/2022/12/accumulators-and-decumulators-2.page" target="_blank" rel="noreferrer">IFEC: accumulator mechanics ↗</a></p></section>}

export default function RiskAnalysis(){const stress20=equityStress(20);const stress35=equityStress(35);const credit=-allocation.find(a=>a.name==='Credit / borrowing')!.value;const cad=currencies.find(c=>c.name==='CAD')!;const jpy=currencies.find(c=>c.name==='JPY')!;return <div className="stack">
 <section className="panel"><p className="eyebrow">RISK SNAPSHOT · 7 SEPTEMBER 2026</p><h2>Overall risk: High · 8/10</h2><p className="subtitle">The rating reflects leverage, equity exposure above net value, short-option obligations and four 2× structured contracts. It is an analytical rating of this statement, not the bank’s suitability classification.</p><div className="risk-grid"><article className="risk-metric"><span>Equity allocation</span><strong>{(metrics.equity/nav*100).toFixed(2)}%</strong><p>{money(metrics.equity)} against {money(nav)} net value</p></article><article className="risk-metric"><span>Fixed advances</span><strong>{(credit/nav*100).toFixed(2)}%</strong><p>{money(credit)} liability including accrued interest</p></article><article className="risk-metric"><span>Later-expiry short puts</span><strong>{laterPuts.length}</strong><p>{money(metrics.futurePutCash)} gross strike purchases if all assigned</p></article><article className="risk-metric"><span>2× contracts</span><strong>{structured.length}</strong><p>Three accumulators and one currency TARF</p></article></div></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">EQUITY STRESS · SIMPLE ILLUSTRATION</p><h2>Large drawdowns are amplified against net value</h2><div className="bridge"><div><span>20% fall in bank equity allocation</span><b>{money(stress20.loss)} loss · {stress20.navDeclinePct.toFixed(1)}% of net value</b></div><div><span>35% fall in bank equity allocation</span><b>{money(stress35.loss)} loss · {stress35.navDeclinePct.toFixed(1)}% of net value</b></div></div><p className="note below">This applies one decline to the ending equity allocation and holds every other position fixed. It is not a forecast, margin calculation or full stress test; options and structured products can change nonlinearly.</p></section><section className="panel"><p className="eyebrow">CURRENCY AND FUNDING</p><h2>Borrowing is concentrated across seven currencies</h2><p>{loans.length} fixed advances mature between {date(loans.map(x=>x.maturity_date!).sort()[0])} and {date(loans.map(x=>x.maturity_date!).sort().at(-1)!)} on the statement. The largest negative allocation is {cad.name} at {money(cad.value)}, followed by {jpy.name} at {money(jpy.value)}.</p><p className="note below">The maturities are statement terms. Current repayment or refinancing status is unknown. Currency allocations include investments and derivatives as well as cash and loans.</p></section></div>
 <section className="panel"><p className="eyebrow">CONTINUED GROWTH</p><h2>Growth durability: Uncertain · 5/10</h2><p className="subtitle">The bank reports +{summary.returnPct.toFixed(2)}% for 2026 through 7 September, including +8.05% in August after −9.25% in March. The gain is real within the statement, but the path is volatile and the source does not attribute the return by holding, leverage or strategy.</p><div className="risk-findings"><article><h3>Positive momentum</h3><p>Investment change is {money(summary.investmentChange)} after net withdrawals, and the performance ending value reconciles to the holdings total.</p></article><article><h3>Fragile funding</h3><p>Borrowing and conditional purchase obligations can force sales during a decline, which can interrupt compounding.</p></article><article><h3>Opaque payoff risk</h3><p>Structured notes, accumulators and the TARF require complete term sheets before downside and cash calls can be bounded.</p></article><article><h3>Missing attribution</h3><p>No transaction ledger or holding-level performance contribution is supplied, so repeatability cannot be separated from market direction.</p></article></div></section>
 <StructuredContracts/>
 <section className="panel"><h2>What could change this rating</h2><ul className="risk-list">{coverage.missing.map(x=><li key={x}>{x}</li>)}<li>Current option settlements, collateral blocks and remaining private-fund capital calls.</li></ul><p className="note below">The holdings inventory and performance section both reconcile to {money(nav,'USD',2)}. This improves confidence in the snapshot total while leaving future risk uncertain.</p><a className="risk-link" href="#reduce-risk">Open the itemized risk-reduction plan →</a></section>
 </div>}
