'use client';
import {useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import source from '@/data/standard-chartered.json';
import fundGuide from '@/data/standard-chartered-fund-guide.json';

const usd=(n:number,digits=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n);
const pct=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;
const wholeEstimates:Record<string,number>={'sc-fund-05':506388,'sc-fund-07':292890};
const weight=(n:number)=>`${(n/source.reported_total_value_usd*100).toFixed(2)}%`;
const valueText=(f:typeof source.funds[number])=>f.value_usd===null?`≈ ${usd(wholeEstimates[f.id],0)}`:usd(f.value_usd);

export default function StandardChartered(){const [sort,setSort]=useState('source');const funds=[...source.funds].sort((a,b)=>sort==='value'?((b.value_usd??wholeEstimates[b.id])-(a.value_usd??wholeEstimates[a.id])):a.id.localeCompare(b.id));return <div className="stack">
 <section className="panel"><p className="eyebrow">STANDARD CHARTERED · MUTUAL FUNDS (NEW)</p><h2>Your 10 funds, in one view</h2><p className="subtitle">A separate Standard Chartered investment snapshot; its holdings are not added to the LGT totals.</p><div className="option-metrics"><article><span>Total funds value</span><strong>{usd(source.reported_total_value_usd)}</strong><p>Gross investment value; excludes any account borrowing</p></article><article><span>Total unrealized gain</span><strong className="positive">{usd(source.reported_unrealized_gain_usd)}</strong><p>{pct(source.reported_unrealized_gain_pct)} reported unrealized gain; no return period given</p></article><article><span>Fund holdings</span><strong>{source.reported_fund_count}</strong><p>Mutual fund investments</p></article></div></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">REPORTED FUND ALLOCATION</p><h2>More than half is in multi-asset funds</h2><div className="allocation below">{source.reported_allocation.map((a,i)=><div className="allocrow" key={a.asset_class}><div><span>{a.asset_class}</span><b>≈ {usd(source.reported_total_value_usd*a.weight_pct/100,0)}</b></div><div className="bartrack"><div className="bar" style={{width:`${a.weight_pct}%`,background:['#168e83','#254b86','#3c92cd'][i]}}/></div><span>{a.weight_pct.toFixed(2)}%</span></div>)}</div><p className="note below">Dollar amounts are calculated from rounded percentages. These are the reported fund categories, not a full look-through allocation. The 33.31% equity category excludes equities held inside multi-asset funds.</p></section><section className="panel"><p className="eyebrow">WHAT THE GAIN MEANS</p><h2>Unrealized gains are only part of the return</h2><p className="subtitle">The +5.48% figure is the reported unrealized gain measure. It does not establish annual performance, total income received or a return after borrowing costs.</p><p className="below">Several share-class labels indicate distributions. Cash already paid out, subscriptions, redemptions, fees and financing costs are not itemized in this snapshot.</p><p className="note below">Amundi Signature CIO Growth reports a gain of {usd(83278.75)} (+29.74%). A gain since purchase cannot be compared fairly with another fund unless the investment periods and cash flows are aligned.</p></section></div>
 <section className="panel"><div className="panelhead"><div><p className="eyebrow">FUND-BY-FUND INVENTORY</p><h2>Fund values and unrealized gains</h2></div><div className="picker"><span className="fieldlabel">Fund order</span><Select value={sort} onValueChange={v=>{if(v)setSort(v)}}><SelectTrigger aria-label="Standard Chartered fund order"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="source">Original order</SelectItem><SelectItem value="value">Largest value first</SelectItem></SelectContent></Select></div></div><Table><TableHeader><TableRow><TableHead>Fund / share class</TableHead><TableHead className="num">Value · USD</TableHead><TableHead className="num">Share of fund total</TableHead><TableHead className="num">Unrealized gain / loss</TableHead><TableHead className="num">Gain / loss %</TableHead></TableRow></TableHeader><TableBody>{funds.map(f=><TableRow key={f.id}><TableCell className="holding-name"><strong>{f.id==='sc-fund-10'?'Signature Select US Allocation · VCC':f.name_as_read}</strong></TableCell><TableCell className="num">{valueText(f)}</TableCell><TableCell className="num">{f.value_usd===null?'≈ ':''}{weight(f.value_usd??wholeEstimates[f.id])}</TableCell><TableCell className={`num ${f.unrealized_gain_usd!==null&&f.unrealized_gain_usd<0?'negative-text':'positive'}`}>{f.unrealized_gain_usd===null?'—':usd(f.unrealized_gain_usd)}</TableCell><TableCell className={`num ${f.unrealized_gain_pct!==null&&f.unrealized_gain_pct<0?'negative-text':''}`}>{f.unrealized_gain_pct===null?'—':pct(f.unrealized_gain_pct)}</TableCell></TableRow>)}</TableBody></Table><p className="note below">Display currency is USD; that alone does not establish underlying currency exposure or hedging.</p></section>
 <section className="panel"><p className="eyebrow">WHAT EACH FUND DOES</p><h2>Names do not always describe the asset class</h2><p className="subtitle">Manager descriptions below explain the mandates. They are separate from the reported category percentages and do not establish the current underlying weights or a verified share-class ISIN.</p><div className="risk-findings">{fundGuide.map(g=><article key={g.id}><h3>{source.funds.find(f=>f.id===g.id)!.name_as_read.split(' PORTFOLIO')[0].split(' FUND')[0]}</h3><p><strong>{g.mandate}</strong></p><p className="note below">{g.note}</p><a className="risk-link" href={g.url} target="_blank" rel="noreferrer">Manager information ↗</a></article>)}</div><p className="note below">Fund payouts and investment returns differ: a distribution can accompany a fall in value, and some funds can distribute capital. Total-return analysis needs distributions, prices and dated cash flows. Public manager links may show a different share class; only the fund-level mandate is used unless the class is explicitly verified.</p></section>
 <section className="panel"><p className="eyebrow">INITIAL RISK SNAPSHOT</p><h2>Fund variety helps, but the underlying overlap is still unknown</h2><div className="risk-findings"><article><h3>Equity risk extends into multi-asset funds</h3><p>Multi-Asset and Equity together account for 85.23% of the reported fund categories. Multi-asset products can hold shares as well as bonds, so the actual stock exposure needs a look-through report.</p></article><article><h3>The biggest individual fund is about 15%</h3><p>AB American Growth represents {weight(594616.38)} of the fund total. The three AB funds together represent {weight(492131.12+594616.38+414385.02)}. That is a manager allocation, not an unsecured loan exposure to the manager.</p></article><article><h3>Money-market units are not bank cash</h3><p>Franklin’s fund is {usd(585739.38)} with a reported unrealized loss of {usd(760.62)}. The snapshot does not show distributions, redemption timing or whether units are pledged as collateral.</p></article><article><h3>Borrowing and total returns need separate records</h3><p>The supplied figures do not show financing, fees, tax, distributions or fund-level holdings. A full risk score or net account value would be premature from this source alone.</p></article></div><p className="note below">Review priorities: obtain the holdings export with ISINs, units and price dates; the distribution and transaction history; the latest fund factsheets; and the account’s current borrowing, collateral and redemption availability.</p></section>
 </div>}
