'use client';
import {useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import source from '@/data/standard-chartered.json';
import fundGuide from '@/data/standard-chartered-fund-guide.json';

const usd=(n:number,digits=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n);
const pct=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;
const wholeEstimates:Record<string,number>={'sc-fund-05':506388,'sc-fund-07':292890};
const weight=(n:number)=>`${(n/source.reported_total_value_usd*100).toFixed(2)}%`;
const valueText=(f:typeof source.funds[number])=>f.value_usd===null?`≈ ${usd(wholeEstimates[f.id],0)}`:usd(f.value_usd);

export default function StandardChartered(){const [sort,setSort]=useState('source');const funds=[...source.funds].sort((a,b)=>sort==='value'?((b.value_usd??wholeEstimates[b.id])-(a.value_usd??wholeEstimates[a.id])):a.id.localeCompare(b.id));return <div className="stack">
 <section className="panel"><p className="eyebrow">STANDARD CHARTERED · MUTUAL FUNDS (NEW)</p><h2>Your 10 funds, in one view</h2><p className="subtitle">Transcribed from the two mobile-app photographs. This is a separate Standard Chartered snapshot; its holdings are not added to the LGT totals.</p><div className="option-metrics"><article><span>Total funds value</span><strong>{usd(source.reported_total_value_usd)}</strong><p>Gross investment value shown by the app; excludes any account borrowing</p></article><article><span>Total unrealized gain</span><strong className="positive">{usd(source.reported_unrealized_gain_usd)}</strong><p>{pct(source.reported_unrealized_gain_pct)} shown by the app; no return period given</p></article><article><span>Fund holdings</span><strong>{source.reported_fund_count}</strong><p>8 exact values readable; 2 values shown approximately because of glare</p></article></div><div className="callout"><h3>Date shown by the source: 08 Sep 2026</h3><p>The device reads “Mon 7 Sep.” The mismatch is retained for confirmation; the displayed fund date is not treated as a verified live valuation date.</p></div></section>
 <div className="overview-grid"><section className="panel"><p className="eyebrow">ALLOCATION REPORTED BY THE APP</p><h2>More than half is in multi-asset funds</h2><div className="allocation below">{source.reported_allocation.map((a,i)=><div className="allocrow" key={a.asset_class}><div><span>{a.asset_class}</span><b>≈ {usd(source.reported_total_value_usd*a.weight_pct/100,0)}</b></div><div className="bartrack"><div className="bar" style={{width:`${a.weight_pct}%`,background:['#168e83','#254b86','#3c92cd'][i]}}/></div><span>{a.weight_pct.toFixed(2)}%</span></div>)}</div><p className="note below">Dollar amounts are calculated from rounded percentages. These are the app’s fund categories, not a full look-through allocation. The 33.31% equity category excludes equities held inside multi-asset funds.</p></section><section className="panel"><p className="eyebrow">WHAT THE GAIN MEANS</p><h2>Unrealized gains are only part of the return</h2><p className="subtitle">The +5.48% figure is the app’s unrealized gain measure. It does not establish annual performance, total income received or a return after borrowing costs.</p><p className="below">Several share-class labels indicate distributions. Cash already paid out, subscriptions, redemptions, fees and financing costs are not itemized in these photographs.</p><p className="note below">The largest readable gain is Amundi Signature CIO Growth: {usd(83278.75)} (+29.74%). A gain since purchase cannot be compared fairly with another fund unless the investment periods and cash flows are aligned.</p></section></div>
 <section className="panel"><div className="panelhead"><div><p className="eyebrow">FUND-BY-FUND INVENTORY</p><h2>Values and gains shown in the photographs</h2></div><div className="picker"><span className="fieldlabel">Fund order</span><Select value={sort} onValueChange={v=>{if(v)setSort(v)}}><SelectTrigger aria-label="Standard Chartered fund order"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="source">As shown in the app</SelectItem><SelectItem value="value">Largest value first</SelectItem></SelectContent></Select></div></div><Table><TableHeader><TableRow><TableHead>Fund / share class as read</TableHead><TableHead className="num">Value · USD</TableHead><TableHead className="num">Share of fund total</TableHead><TableHead className="num">Unrealized gain / loss</TableHead><TableHead className="num">Gain / loss %</TableHead><TableHead>Source clarity</TableHead></TableRow></TableHeader><TableBody>{funds.map(f=><TableRow key={f.id}><TableCell className="holding-name"><strong>{f.id==='sc-fund-10'?'Signature Select US Allocation · VCC':f.name_as_read}</strong>{f.id==='sc-fund-10'&&<span>Exact vehicle prefix and share-class suffix partly obscured.</span>}</TableCell><TableCell className="num">{valueText(f)}</TableCell><TableCell className="num">{f.value_usd===null?'≈ ':''}{weight(f.value_usd??wholeEstimates[f.id])}</TableCell><TableCell className={`num ${f.unrealized_gain_usd!==null&&f.unrealized_gain_usd<0?'negative-text':'positive'}`}>{f.unrealized_gain_usd===null?'Not legible':usd(f.unrealized_gain_usd)}</TableCell><TableCell className={`num ${f.unrealized_gain_pct!==null&&f.unrealized_gain_pct<0?'negative-text':''}`}>{f.unrealized_gain_pct===null?'Not legible':pct(f.unrealized_gain_pct)}</TableCell><TableCell className="wrap risk-table-text"><details><summary>{f.value_usd===null?'Value cents obscured':f.unrealized_gain_usd===null?'Gain obscured':f.id==='sc-fund-10'?'Name partly obscured':'Figures readable'}</summary><p className="note below">{f.reading_note}</p><p className="source">{f.source_images.join(' · ')}</p></details></TableCell></TableRow>)}</TableBody></Table><p className="note below">≈ values use the readable whole-dollar portion only. No exact cents or unreadable BGF gain have been filled in from arithmetic. Display currency is USD; that alone does not establish underlying currency exposure or hedging.</p></section>
 <section className="panel"><p className="eyebrow">WHAT EACH FUND DOES</p><h2>Names do not always describe the asset class</h2><p className="subtitle">Manager descriptions below explain the mandates. They are separate from the app’s category percentages and do not establish the current underlying weights or a verified share-class ISIN.</p><div className="risk-findings">{fundGuide.map(g=><article key={g.id}><h3>{source.funds.find(f=>f.id===g.id)!.name_as_read.split(' PORTFOLIO')[0].split(' FUND')[0]}</h3><p><strong>{g.mandate}</strong></p><p className="note below">{g.note}</p><a className="risk-link" href={g.url} target="_blank" rel="noreferrer">Manager information ↗</a></article>)}</div><p className="note below">Fund payouts and investment returns differ: a distribution can accompany a fall in value, and some funds can distribute capital. Total-return analysis needs distributions, prices and dated cash flows. Public manager links may show a different share class; only the fund-level mandate is used unless the class is explicitly verified.</p></section>
 <section className="panel"><p className="eyebrow">INITIAL RISK SNAPSHOT</p><h2>Fund variety helps, but the underlying overlap is still unknown</h2><div className="risk-findings"><article><h3>Equity risk extends into multi-asset funds</h3><p>Multi-Asset and Equity together account for 85.23% of the app’s fund categories. Multi-asset products can hold shares as well as bonds, so the actual stock exposure needs a look-through report.</p></article><article><h3>The biggest individual fund is about 15%</h3><p>AB American Growth represents {weight(594616.38)} of the fund total. The three AB funds together represent {weight(492131.12+594616.38+414385.02)}. That is a manager allocation, not an unsecured loan exposure to the manager.</p></article><article><h3>Money-market units are not bank cash</h3><p>Franklin’s fund is {usd(585739.38)} with a reported unrealized loss of {usd(760.62)}. The photographs do not show distributions, redemption timing or whether units are pledged as collateral.</p></article><article><h3>Borrowing and total returns need separate records</h3><p>These screenshots do not show financing, fees, tax, distributions or fund-level holdings. A full risk score or net account value would be premature from this source alone.</p></article></div><p className="note below">Review priorities: obtain the holdings export with ISINs, units and price dates; the distribution and transaction history; the latest fund factsheets; and the account’s current borrowing, collateral and redemption availability.</p></section>
 <section className="panel"><p className="eyebrow">FINDING THIS VIEW ONLINE · CHECKED 7 SEP 2026</p><h2>Mobile route confirmed; desktop equivalent not located</h2><div className="bridge"><div><span>Path you used in the mobile app</span><b>☰ → Investing → Mutual Funds (New)</b></div><div><span>Observed online-banking Invest menu</span><b>Investment Profile · Market views on-the-go</b></div></div><p className="below">The web Investment Profile opens the risk questionnaire/profile, not the mutual-fund holdings. No Mutual Funds link appeared in the account dashboard or its Invest menu. After signing back in, Service Requests exposed Account Management, Card Management and Personal Details, with no investment category or holdings link found. No service request was submitted.</p><p className="below">Standard Chartered Kenya’s <a href="https://www.sc.com/ke/investments/mutual-funds/" target="_blank" rel="noreferrer">mutual-funds guide ↗</a> directs portfolio tracking through SC Mobile. Its <a href="https://www.sc.com/ke/sc-mobile/" target="_blank" rel="noreferrer">SC Mobile page ↗</a> also places “Online Mutual Funds” in the app. Neither source establishes a desktop route or proves the feature is mobile-only.</p><div className="callout below"><h3>The precise question for Standard Chartered</h3><p>“Does Kenya’s Mutual Funds (New) holdings screen have a supported desktop-browser entry point for my account? If so, what is the official route, and does it require separate enrollment?”</p></div></section>
 <section className="panel"><p className="eyebrow">SOURCE CHECK</p><h2>Reported totals are preserved independently of the row readings</h2><p>The eight clearly readable fund values total {usd(source.reconciliation.readable_value_sum_usd)}. The remaining {usd(source.reconciliation.combined_value_residual_for_two_obscured_rows_usd)} is the combined arithmetic residual for Allianz Income and Growth and Amundi CIO Income, not a verified individual reading.</p><p className="below">Nine readable gains total {usd(source.reconciliation.readable_gain_sum_usd)}. The {usd(source.reconciliation.unreadable_bgf_gain_residual_usd)} residual is not presented as a verified BGF gain. The app’s allocation percentages sum to 100%.</p><p className="note below">Sources: 1000021018.jpg and 1000021019.jpg supplied by you. Fund identities use the visible names; no ISINs or missing share-class details are invented. Original photographs, personal identifiers and banking-session links are not included in the published page.</p></section>
 </div>}
