import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import source from '@/data/tcg-qcam.json';

const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:1,maximumFractionDigits:1}).format(n);
const pct=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;
const date=(s:string)=>new Date(`${s}T12:00:00Z`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
const pairs=(x:Record<string,number>)=>Object.entries(x).map(([name,value])=>({name,value}));

function Allocation({title,values}:{title:string;values:Record<string,number>}){
 const rows=pairs(values);const max=Math.max(...rows.map(x=>Math.abs(x.value)));
 return <section className="panel"><p className="eyebrow">CAPITAL DEPLOYMENT</p><h2>{title}</h2><div className="allocation below">{rows.map(x=><div className="allocrow" key={x.name}><div><span>{x.name}</span></div><div className="bartrack"><div className="bar" style={{width:`${Math.abs(x.value)/max*100}%`}}/></div><span>{x.value}%</span></div>)}</div></section>
}

export default function TcgQcam(){
 return <div className="stack">
  <section className="panel tcg-intro"><div><p className="eyebrow">TCG QCAM · SEPARATE ACCOUNT</p><h2>Account value and reported return</h2><p className="subtitle">The figures below reproduce the 31 August 2026 statement. They are not added to either bank portfolio.</p></div><span className="tcg-rating">VERIFY BEFORE ADDING FUNDS</span><div className="option-metrics tcg-metrics"><article><span>Current portfolio value</span><strong>{usd(source.current_portfolio_value)}</strong><p>Statement-described liquidation value</p></article><article><span>Net capital invested</span><strong>{usd(source.net_capital_invested)}</strong><p>After reported capital redemptions</p></article><article><span>Lifetime profit</span><strong className="positive">{usd(source.lifetime_profit)}</strong><p>{(source.lifetime_profit/source.net_capital_invested*100).toFixed(2)}% of net capital invested</p></article></div><div className="risk-grid"><article className="risk-metric"><span>Running XIRR</span><strong>{pct(source.running_xirr_pct)}</strong><p>Annualized and reported net of fees</p></article><article className="risk-metric"><span>August profit</span><strong>{usd(source.monthly_profit)}</strong><p>{pct(source.monthly_return_pct)} on weighted-average capital</p></article><article className="risk-metric"><span>Reported Sharpe</span><strong>{source.monthly_history.at(-1)!.sharpe.toFixed(1)}</strong><p>Annualized from monthly returns</p></article><article className="risk-metric"><span>High-water mark</span><strong>{source.high_watermark_month}</strong><p>Statement-reported fee reference month</p></article></div></section>
  <div className="overview-grid"><Allocation title="During August 2026" values={source.allocation_current_pct}/><Allocation title="Since inception" values={source.allocation_lifetime_pct}/></div>
  <section className="panel"><p className="eyebrow">TRAILING 12 MONTHS</p><h2>Reported monthly results</h2><Table><TableHeader><TableRow><TableHead>Month</TableHead><TableHead className="num">Profit / loss</TableHead><TableHead className="num">Running XIRR</TableHead><TableHead className="num">Sharpe</TableHead><TableHead className="num">Cumulative P/L</TableHead><TableHead className="num">Account value</TableHead></TableRow></TableHeader><TableBody>{source.monthly_history.map(r=><TableRow key={r.month}><TableCell>{r.month}</TableCell><TableCell className={`num ${r.profit_loss<0?'negative-text':'positive'}`}>{usd(r.profit_loss)}</TableCell><TableCell className="num">{pct(r.running_xirr_pct)}</TableCell><TableCell className="num">{r.sharpe.toFixed(1)}</TableCell><TableCell className="num">{usd(r.cumulative_profit_loss)}</TableCell><TableCell className="num">{usd(r.account_value)}</TableCell></TableRow>)}</TableBody></Table><p className="note below">The statement says Sharpe is annualized from monthly returns after three months of investment. The account began before this 12-month table, so these rows do not sum to lifetime profit.</p></section>
  <div className="overview-grid"><section className="panel"><p className="eyebrow">CURRENT LOOK-THROUGH</p><h2>August sector exposure</h2><div className="tcg-sector-grid">{pairs(source.sector_current_pct).map(x=><div key={x.name}><span>{x.name}</span><b>{x.value}%</b></div>)}</div><p className="note below">Technology and index instruments account for 69% of the reported equity look-through during the month. “Long/Inverse ETF” labels indicate directional and hedging strategies, but the statement does not provide tickers, quantities or gross exposure.</p></section><section className="panel"><p className="eyebrow">MONTH-END HOLDINGS</p><h2>Four positions were named</h2><ol className="action-list compact">{source.month_end_top_holdings.map(x=><li key={x}>{x}</li>)}</ol><p className="note">The report also lists ten frequently traded names, including sector, index and inverse ETFs. It does not show complete month-end positions or market values.</p></section></div>
  <section className="panel"><p className="eyebrow">CAPITAL HISTORY</p><h2>Five reported contributions</h2><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Event</TableHead><TableHead className="num">Amount</TableHead><TableHead className="num">Cumulative capital</TableHead></TableRow></TableHeader><TableBody>{source.transactions.map(r=><TableRow key={r.date}><TableCell>{date(r.date)}</TableCell><TableCell>{r.event}</TableCell><TableCell className="num">{usd(r.amount)}</TableCell><TableCell className="num">{usd(r.cumulative_amount)}</TableCell></TableRow>)}</TableBody></Table><p className="note below">The transaction page reports no capital redemptions or profit withdrawals. The five contributions total {usd(source.net_capital_invested)}.</p></section>
  <section className="panel tcg-verdict"><div><p className="eyebrow">INDEPENDENT CHECK · 07 SEP 2026</p><h2>Scam assessment: not proven, but verification risk is high</h2><p className="subtitle">The statement is arithmetically coherent and the group has a public website and investor app. That is not enough to confirm that the account value, custody, regulatory permissions or performance are genuine.</p></div><span className="tcg-rating danger">HIGH VERIFICATION RISK</span><div className="risk-findings"><article><h3>What supports legitimacy</h3><p>Net capital plus lifetime profit equals the reported account value exactly. The contribution history also reconciles to net capital. TIW Capital Group publishes a QCAM description that says trading occurs in the client’s own brokerage account.</p></article><article><h3>What the statement cannot prove</h3><p>It is a group-produced report, not an independent broker or custodian statement. It omits the contracting legal entity, licence number, custodian, broker, account ownership, security identifiers, quantities, prices, fees and independently audited performance.</p></article><article><h3>Return claims need stronger evidence</h3><p>The group brochure markets 15%+ expected annual returns with “high consistency” and a moderate risk profile. This statement reports Sharpe ratios from 4.6 to 8.8. Those are unusually strong figures and need a full return series, drawdowns and independent verification before they should be trusted.</p></article><article><h3>Regulatory identity is unresolved</h3><p>A search of the current Kenya CMA licence pages did not locate TIW, TCG or QCAM. The group website says its services may not be licensed in every jurisdiction, and describes the named Dubai company as an algorithm-technology owner rather than the manager or custodian.</p></article><article><h3>One Singapore entity was struck off</h3><p>Singapore’s official gazette lists TIW Capital Global Pte. Ltd. (202309761R) among companies struck off in September 2024. The statement does not name that entity, so this is a question to resolve, not proof that it operated this account.</p></article><article><h3>Reverse-solicitation language deserves care</h3><p>The product page asks visitors to confirm that they approached the company without solicitation. Only make that declaration if it is factually true; it can affect how cross-border marketing restrictions are analyzed.</p></article></div></section>
  <section className="panel"><p className="eyebrow">BEFORE SENDING MORE MONEY</p><h2>Documents and confirmations to demand</h2><ol className="action-list"><li><h3>Identify every legal party</h3><p>Get the full contracting manager, adviser, broker, custodian and administrator names, jurisdictions, registration numbers and licence numbers.</p></li><li><h3>Verify licences directly</h3><p>Check each number with the relevant regulator using contact details from the regulator’s own website. Do not rely on certificates or links sent by a salesperson.</p></li><li><h3>Confirm custody independently</h3><p>Log in to the broker or custodian through an independently verified address and confirm that the account is in the investor’s name, the positions exist, and the manager cannot withdraw cash.</p></li><li><h3>Reconcile contract notes</h3><p>Match every trade and cash movement to broker statements. Ask for the complete month-end holdings file with tickers, quantities, prices, leverage, shorts, derivatives and margin.</p></li><li><h3>Test liquidity and performance</h3><p>Request audited, administrator-verified returns, fee calculations and maximum drawdown. Before adding funds, independently confirm the withdrawal process and complete a modest withdrawal through the custodian.</p></li><li><h3>Resolve the Singapore history</h3><p>Ask whether TIW Capital Global Pte. Ltd. was involved, why it was struck off, and which current entity assumed any contracts or obligations.</p></li></ol><div className="tcg-links"><a href="https://licensees.cma.or.ke/" target="_blank" rel="noreferrer">Kenya CMA licence directory ↗</a><a href="https://eservices.mas.gov.sg/fid/institution?category=Approved" target="_blank" rel="noreferrer">Singapore MAS directory ↗</a><a href="https://opr.fscmauritius.org/ords/opr/r/fsc-opr/fsc-online-public-register-opr" target="_blank" rel="noreferrer">Mauritius FSC register ↗</a><a href="https://assets.egazette.gov.sg/2024/Government%20Gazette/Notices%20under%20other%20Acts/2822.pdf" target="_blank" rel="noreferrer">Singapore striking-off gazette ↗</a><a href="https://tiwcg.com/wp-content/uploads/2025/11/TIW-Brochure.pdf" target="_blank" rel="noreferrer">TCG product brochure ↗</a><a href="https://tiwcg.com/product-services/" target="_blank" rel="noreferrer">TCG product disclosures ↗</a></div><p className="note below">This review assesses the supplied statement and public records. It does not determine fraud or verify ownership of assets.</p></section>
 </div>
}
